{{- if $.Values.global.render -}}
{{- range $key, $val := $.Values.apps }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.resource.name }}-{{ $key }}
  namespace: {{ $.Values.resource.namespace }}    
  labels:
    account: {{ $key }}
  {{- if $.Values.global.argocd.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: "15"
  {{- end }}
{{- end }}
{{- end -}}