{{- if $.Values.global.render -}}
{{- if $.Values.global.namespace.enabled -}}
{{- range $.Values.clusterrole }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .roleref.name }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: {{ .subjects.kind }}
  name: {{ .subjects.name }}
{{- end }}  
{{- end -}}
{{- end -}} 