{{- if $.Values.global.render -}}
{{- if $.Values.global.operators.enabled -}}
{{- if $.Values.operators.nmstate.enabled -}}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: openshift-nmstate-
  annotations:
    olm.providedAPIs: NMState.v1.nmstate.io
{{- if $.Values.global.argocd.enabled }}
    argocd.argoproj.io/sync-wave: "0"
{{- end }}
  name: openshift-nmstate-sno
  namespace: {{ $.Values.nmstate.namespace }}
spec:
  targetNamespaces:
    - openshift-nmstate
  upgradeStrategy: Default
{{- end -}}
{{- end -}}
{{- end -}}
